// Export all pages
export { Login } from './Login'
export { Register } from './Register'
export { Home } from './Home'
export { VideoPlayer } from './VideoPlayer'
export { Channel } from './Channel'
export { Search } from './Search'
export { Playlists } from './Playlists'
export { Profile } from './Profile'
export { Upload } from './Upload'
export { History } from './History'
export { Subscriptions } from './Subscriptions'
export { LandingPage } from './LandingPage'
export { PlaylistDetailPage } from './PlaylistDetailPage'
export { Pricing } from './Pricing'
export { Contact } from './Contact'
